version: 2.1

jobs:
  create_tag:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: git tag -a ${CIRCLE_BRANCH#release-} -m "Release ${CIRCLE_BRANCH#release-}"
      - run: git push origin ${CIRCLE_BRANCH#release-} --tags
    filters:
      branches:
        only: main
        # This will run the job only if the previous branch was a release branch
        previous: /^release-.*$/

  push_podspec:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: pod trunk push ZeotapCollect.podspec
    filters:
      branches:
        only: main
        # This will run the job only if the previous branch was a release branch
        previous: /^release-.*$/
        
workflows:
  build_and_test:
    jobs:
      - create_tag
      - push_podspec:
          requires:
            - create_tag
    # This is the filter that will only run the workflow when the release branch is merged into main
    filters:
      branches:
        only: main
        branches: /^release-.*$/ 


