jobs:
  create_tag:
    macos:
      xcode: 12.5.1

    steps:
      - checkout
      - run: git tag -a ${CIRCLE_BRANCH#release-} -m "Release ${CIRCLE_BRANCH#release-}"
      - run: git push origin ${CIRCLE_BRANCH#release-} --tags
    when: << pipeline.parameters.branch == 'main' && pipeline.parameters.branch_previous == ('release-' + * ) >>

  push_podspec:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: pod trunk push ZeotapCollect.podspec
    when: << pipeline.parameters.branch == 'main' && pipeline.parameters.branch_previous == ('release-' + * ) >>

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - create_tag
      - push_podspec:
         requires:
          - create_tag
    # This is the filter that will only run the workflow when the release branch is merged into main
    filters:
      branches:
        only: main
